package Interfaces;

public interface Comunicable {
    //COMPORTAMIENTO QUE LA CLASE QUE IMPLEMENTE ESTA INTRFAZ ESTA OBLIGADA A USAR ESTE METODO
    // NO PODEMOS TENER ATRIBUTOS PRIVATE POR LO TANTO NO PODEMOS TENER GETTERS Y SETTERS
    
    // PUEDE TENER SOLO CONSTANTES EJEMPLO:
    // static final GRITO = "aaaaah"

      void comunicarse(); // POR DEFECTO SIN PONER ABSTRACT YA ELLENGUAJE LO INTERPRETA  
}
